#!/system/bin/sh
# nano: wrapper to set up and run nano from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

if [ "$1" == "--term" ]; then
  term=$2;
  shift 2;
else
  term=screen;
fi;

clear;
resize >/dev/null;
TERMINFO=/system/usr/share/terminfo TERM=$term $dir/nano.bin "$@";
